<template>
  <div>
    <p>
      <v-button
        type="button"
        shape="radius"
        theme="primary"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Primary
      </v-button>
      <v-button
        type="button"
        shape="radius"
        theme="default"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Default
      </v-button>
      <v-button
        type="button"
        shape="radius"
        theme="warning"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Warning
      </v-button>
      <v-button
        type="button"
        shape="radius"
        theme="danger"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Danger
      </v-button>
    </p>
    <p>
      <v-button
        type="button"
        shape="radius"
        theme="primary"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Primary
      </v-button>
      <v-button
        type="button"
        shape="radius"
        theme="default"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Default
      </v-button>
      <v-button
        type="button"
        shape="radius"
        theme="warning"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Warning
      </v-button>
      <v-button
        type="button"
        shape="radius"
        theme="danger"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Danger
      </v-button>
    </p>
    <p>
      <v-button
        type="text"
        shape="radius"
        theme="primary"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Primary
      </v-button>
      <v-button
        type="text"
        shape="radius"
        theme="default"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Default
      </v-button>
      <v-button
        type="text"
        shape="radius"
        theme="warning"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Warning
      </v-button>
      <v-button
        type="text"
        shape="radius"
        theme="danger"
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Danger
      </v-button>
    </p>
    <p>
      <v-button
        type="text"
        shape="radius"
        theme="primary"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Primary
      </v-button>
      <v-button
        type="text"
        shape="radius"
        theme="default"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Default
      </v-button>
      <v-button
        type="text"
        shape="radius"
        theme="warning"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Warning
      </v-button>
      <v-button
        type="text"
        shape="radius"
        theme="danger"
        disabled
        prefix-icon="v-icon-loading"
        suffix-icon="v-icon-loading">
        Danger
      </v-button>
    </p>
  </div>
</template>
<script>
  import Button from '@/components/button';

  export default {
    components: {
      VButton: Button,
    },
  };
</script>